substitutions:
  name: lilygo-tdeck-plus
  friendly_name: "LilyGO T-Deck Plus"
  gps_rx_pin: "44"
  gps_tx_pin: "43"
  touch_x_min: "0"
  touch_x_max: "238"
  touch_y_min: "16"
  touch_y_max: "260"

packages:
  board_base:
    url: https://github.com/jloops412/esphome-lilygo-tdeck-plus.git
    ref: v0.7.1-lvgl-modern-ui-shortcuts
    files:
      - esphome/packages/board_base.yaml
      - esphome/packages/persistence_globals.yaml
      - esphome/packages/ha_entities.yaml
      - esphome/packages/gps_uart.yaml
      - esphome/packages/ui_lvgl.yaml
      - esphome/packages/display_mipi_lvgl.yaml
      - esphome/packages/input_touch_gt911_lvgl.yaml
      - esphome/packages/input_trackball_lvgl.yaml
      - esphome/packages/input_keyboard_i2c_lvgl.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name} Fallback"
    password: "esphome1234"
