substitutions:
  name: lilygo-tdeck-plus
  friendly_name: "LilyGO T-Deck Plus"
  gps_rx_pin: "44"
  gps_tx_pin: "43"
  gps_baud_rate: "9600"
  touch_x_min: "0"
  touch_x_max: "238"
  touch_y_min: "16"
  touch_y_max: "260"

packages:
  board_base: !include ../packages/board_base.yaml
  persistence_globals: !include ../packages/persistence_globals.yaml
  ha_entities: !include ../packages/ha_entities.yaml
  gps_uart: !include ../packages/gps_uart.yaml
  ui_lvgl: !include ../packages/ui_lvgl.yaml
  display_mipi_lvgl: !include ../packages/display_mipi_lvgl.yaml
  input_touch_gt911_lvgl: !include ../packages/input_touch_gt911_lvgl.yaml
  input_trackball_lvgl: !include ../packages/input_trackball_lvgl.yaml
  input_keyboard_i2c_lvgl: !include ../packages/input_keyboard_i2c_lvgl.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name} Fallback"
    password: "esphome1234"
