substitutions:
  name: lilygo-tdeck-plus
  friendly_name: "LilyGO T-Deck Plus"
  gps_rx_pin: "44"
  gps_tx_pin: "43"

packages:
  board_base: !include ../packages/board_base.yaml
  persistence_globals: !include ../packages/persistence_globals.yaml
  ha_entities: !include ../packages/ha_entities.yaml
  gps_uart: !include ../packages/gps_uart.yaml
  ui_render_core: !include ../packages/ui_render_core.yaml
  display_mipi_custom: !include ../packages/display_mipi_custom.yaml
  input_touch_gt911: !include ../packages/input_touch_gt911.yaml
  input_trackball: !include ../packages/input_trackball.yaml
  input_keyboard_i2c: !include ../packages/input_keyboard_i2c.yaml
  ui_pages_lights: !include ../packages/ui_pages_lights.yaml
  ui_pages_weather: !include ../packages/ui_pages_weather.yaml
  ui_pages_feeds: !include ../packages/ui_pages_feeds.yaml
  ui_pages_settings: !include ../packages/ui_pages_settings.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name} Fallback"
    password: "esphome1234"
